export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_PORTFOLIO = "GET_PORTFOLIO";
export const PORTFOLIO_LOADING = "PORTFOLIO_LOADING";
export const PORTFOLIO_NOT_FOUND = "PORTFOLIO_NOT_FOUND";
export const CLEAR_CURRENT_PORTFOLIO = "CLEAR_CURRENT_PORTFOLIO";
export const GET_PORTFOLIOS = "GET_PORTFOLIOS";
